name: url-shortener
services:
  backend:
    build:
      context: .
      dockerfile: services/backend/Dockerfile
      target: prod
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:${PORT}"

  frontend:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
      target: prod
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
