name: url-shortener-backend

services:
  dynamodb-local:
    profiles: [dev]
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"

  backend-prod:
    profiles: [prod]
    build:
      context: .
      target: prod
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
